env:
  node: true
  es2021: true

extends:
  - eslint:recommended
  - plugin:import/recommended
  - airbnb
parserOptions:
  ecmaVersion: latest

rules:  
  no-console: 0
  import/extensions: # FIXME: remove when rule will be adjusted for new nodejs version
    - error
    - ignorePackages
    - js: always

  "import/prefer-default-export": "off"